version: '3.3'
services:
  server:
    build: local_attestation/.
    command: ego run server/server
    devices:
      - "/dev/sgx_enclave:dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
      - "/dev/sgx_vepc:/dev/sgx_vepc"

  client:
    depends_on:
      - server
    build: local_attestation/.
    command: ego run client/client
    devices:
      - "/dev/sgx_enclave:dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
      - "/dev/sgx_vepc:/dev/sgx_vepc"